---
- name: Get Active User on Windows
  hosts: "{{ ansible_limit | default(omit) }}"
  gather_facts: no
  tasks:

    - name: Find the currently logged-in user (fully sanitized)
      ansible.windows.win_shell: |
        (Get-WMIObject -Class Win32_ComputerSystem).UserName
      register: logged_in_user_raw

    - name: Strip newline characters in Ansible
      set_fact:
        logged_in_user: "{{ logged_in_user_raw.stdout | trim }}"

    - name: Display final sanitized user
      ansible.builtin.debug:
        msg: "Final sanitized active user is '{{ logged_in_user }}'"
