---
- name: Get MAC address of Windows device
  hosts: "{{ ansible_limit | default(omit) }}"
  gather_facts: no
  tasks:
    - name: Retrieve MAC address using PowerShell
      win_shell: |
        Get-NetAdapter | Select-Object -ExpandProperty MacAddress
      register: mac_address_output

    - name: Display the MAC address
      debug:
        var: mac_address_output.stdout_lines
