---
- name: Install .NET Framework 4.7 on Windows 8
  gather_facts: no
  hosts: "{{ ansible_limit | default(omit) }}"
  tasks:
    - name: Download .NET Framework 4.7 installer
      win_get_url:
        url: "http://172.20.5.10:8000/dotnetfx47.exe"
        dest: "C:\\Users\\{{ ansible_user }}\\Downloads\\dotnetfx47.exe"

    - name: Install .NET Framework 4.7
      win_package:
        path: "C:\\Users\\{{ ansible_user }}\\Downloads\\dotnetfx47.exe"
        arguments: "/quiet /norestart"
        state: present

    #- name: Cleanup - Remove .NET Framework 4.7 installer
     # win_file:
      #  path: "C:\\Users\\{{ ansible_user }}\\Downloads\\dotnetfx47.exe"
       # state: absent
