---
# This playbook uses the win_ping module to test connectivity to Windows hosts
- name: Ping
  hosts: "{{ ansible_limit | default(omit) }}"
  gather_facts: no
  #ignore_unreachable: true

  tasks:
  - name: ping
    win_ping:
