---
- name: Undo user changes and restore disabled accounts
  hosts: "{{ ansible_limit | default(omit) }}"
  gather_facts: no
  tasks:
    - name: Check if script marker file exists
      ansible.windows.win_stat:
        path: C:\Windows\Temp\ansible_disabled_users.txt
      register: disabled_users_marker

    - name: Fail if no disabled users file found
      fail:
        msg: "No disabled user list found. The script was either not run before or marker file is missing."
      when: not disabled_users_marker.stat.exists

    - name: Get list of previously disabled users
      ansible.windows.win_shell: |
        Get-Content C:\Windows\Temp\ansible_disabled_users.txt
      register: disabled_users
      changed_when: false

    - name: Enable previously disabled users
      ansible.windows.win_shell: |
        $users = '{{ disabled_users.stdout_lines | join("','") }}' -split ','
        foreach ($user in $users) {
          if ($user -ne "") {
            Write-Output "Enabling user: $user"
            Enable-LocalUser -Name $user -ErrorAction SilentlyContinue
          }
        }
      register: enable_output
      changed_when: "'Enabling user' in enable_output.stdout"

    - name: Remove the 'exam' user (optional)
      ansible.windows.win_user:
        name: exam
        state: absent
      when: remove_exam | default(false)

    - name: Remove 'exam' user profile folder if it exists
      ansible.windows.win_file:
        path: C:\Users\exam
        state: absent
      when: remove_exam | default(false)

    - name: Remove registry profile entry for 'exam'
      ansible.windows.win_shell: |
        $sid = (New-Object System.Security.Principal.NTAccount("exam")).Translate([System.Security.Principal.SecurityIdentifier]).Value
        $profileKey = "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList\$sid"
        if (Test-Path $profileKey) {
          Remove-Item -Path $profileKey -Force -Recurse
          Write-Output "Profile entry removed: $profileKey"
        } else {
          Write-Output "No profile entry found for exam."
        }
      when: remove_exam | default(false)
      register: remove_profile_output
      changed_when: "'Profile entry removed' in remove_profile_output.stdout"

    - name: Delete marker files to reset state
      ansible.windows.win_file:
        path: "{{ item }}"
        state: absent
      with_items:
        - C:\Windows\Temp\ansible_script_marker.txt
        - C:\Windows\Temp\ansible_disabled_users.txt

    - name: Show re-enabled users
      debug:
        var: enable_output.stdout_lines
#ansible-playbook -i hosts undo_user_changes.yml -e "remove_exam=true"
