---
- name: Confirgure DNS for all adapters
  gather_facts: no
  hosts: "{{ ansible_limit | default(omit) }}"
  tasks:
    - name: Configure all adapters to use specified DNS Servers
      win_dns_client:
        adapter_names: "*"
        ipv4_addresses: "{{ dns-servers }}"
